###############################################################################
#
# Copyright (C) 2025 Tom Kralidis
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################

x-logging: &logging
  logging:
    driver: json-file
    options:
      mode: non-blocking
      max-buffer-size: 100m
      max-size: 10m
      max-file: 1

services:
  msc-wis2node-cache:
    image: redis:latest
    container_name: msc-wis2node-cache
    env_file:
      - msc-wis2node.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 100
    <<: *logging

  msc-wis2node-management:
    image: msc-wis2node-management
    container_name: msc-wis2node-management
    build:
      context: msc-wis2node-management/
    env_file:
      - msc-wis2node.env
    restart: unless-stopped
    volumes:
      # below is required so that the container has certificates required
      # for SSL-enabled connections to internal hosts (geomet-dev-xx.edc-mtl.ec.gc.ca)
      - "/etc/ssl/certs:/etc/ssl/certs:ro" # mount host ssl certs
      - "/usr/local/share/ca-certificates/:/usr/local/share/ca-certificates/:ro" # mount host ca-certificates
    <<: *logging
